"""AletheiaTelos DealFlow Engine — canonical deal record persistence.

One table (`deals`) plus due-diligence tables (`dd_items`, `dd_documents`)
plus charter-analytics tables (`evidence`, `perspectives`, `scenarios`,
`simulations`, `theses`, `outcomes`).
The record is the canonical source of truth:

  identity          deal_id, name, asset_type, location
  original_inputs   the 11 validated financial inputs, exactly as submitted
  underwriting      deterministic results with provenance (from underwriting.py)
  workflow          status, created_at, updated_at, artifact_reference
  contact           name / email / phone as submitted

Rules:
  - Deal IDs are generated by the application as AT-YYYY-NNNNNN from the
    database row id. They never depend on property data.
  - Original inputs are never overwritten by calculations; underwriting
    results live in their own JSON column.
  - Missing information stays explicit (None in inputs, "unavailable" in
    underwriting).
  - Status transitions are human-controlled: NEW -> REVIEWING -> PURSUE/HOLD/PASS,
    with reopening back to REVIEWING allowed. Terminal states cannot jump
    arbitrarily.

The submission path used by the web app AND the import CLI is submit_deal():
  raw intake dict -> validation -> record -> underwriting -> stored record.

Backends:
  - Default: local SQLite file (DEALFLOW_DB env, else dealflow.db next to
    this file). Used for development and the test suite.
  - Production: PostgreSQL when the DATABASE_URL environment variable is set
    (any provider: Render Postgres, Neon, Supabase, ...). Requires the
    `psycopg` package. All SQL is written once with `?` placeholders and
    translated to `%s` for Postgres; the few dialect differences (DDL,
    INSERT ... RETURNING, ON CONFLICT, information_schema) are branched in
    one place each.
"""

import datetime
import json
import os
import sqlite3

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # pragma: no cover - psycopg absent in dev/test envs
    psycopg = None
    dict_row = None

import underwriting
import validation
import evidence as evidence_mod
import journal as journal_mod

REPO_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_DB = os.path.join(REPO_DIR, "dealflow.db")

STATUSES = ("NEW", "REVIEWING", "PURSUE", "HOLD", "PASS")

# ---------- due diligence ----------

DD_STATUSES = ("not_started", "requested", "received", "in_review",
               "cleared", "waived", "issue")

# (category, item_key, label) — the standard CRE checklist seeded for every deal.
DD_CHECKLIST = [
    ("Legal / Title", "purchase_agreement", "Purchase agreement"),
    ("Legal / Title", "title_commitment", "Title commitment"),
    ("Legal / Title", "title_exceptions", "Title exceptions reviewed"),
    ("Legal / Title", "survey", "Survey"),
    ("Legal / Title", "zoning_verification", "Zoning verification"),
    ("Financial", "rent_roll", "Rent roll"),
    ("Financial", "leases", "Leases"),
    ("Financial", "operating_statements", "12-month operating statements"),
    ("Financial", "tax_returns", "Tax returns"),
    ("Financial", "estoppels", "Estoppel certificates"),
    ("Physical / Environmental", "inspection", "Property inspection"),
    ("Physical / Environmental", "phase_i", "Environmental Phase I"),
    ("Physical / Environmental", "major_systems", "Major systems (roof / HVAC)"),
    ("Insurance / Compliance", "insurance_quotes", "Insurance quotes"),
    ("Insurance / Compliance", "flood_zone", "Flood zone determination"),
    ("Insurance / Compliance", "permits_co", "Permits / certificate of occupancy"),
    ("Association", "hoa_docs", "HOA / condo docs (waive if not applicable)"),
    ("Financing", "loan_term_sheet", "Loan term sheet"),
    ("Financing", "appraisal", "Appraisal"),
]

DD_CATEGORIES = []
for _cat, _key, _label in DD_CHECKLIST:
    if _cat not in DD_CATEGORIES:
        DD_CATEGORIES.append(_cat)
del _cat, _key, _label

DD_ITEMS_SCHEMA = """
CREATE TABLE IF NOT EXISTS dd_items (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id   TEXT NOT NULL,
    category  TEXT NOT NULL,
    item_key  TEXT NOT NULL,
    label     TEXT NOT NULL,
    status    TEXT NOT NULL DEFAULT 'not_started',
    notes     TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (deal_id, item_key)
)
"""

DD_DOCUMENTS_SCHEMA = """
CREATE TABLE IF NOT EXISTS dd_documents (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id     TEXT NOT NULL,
    item_key    TEXT NOT NULL,
    filename    TEXT NOT NULL,
    stored_path TEXT NOT NULL,
    note        TEXT NOT NULL DEFAULT '',
    uploaded_at TEXT NOT NULL
)
"""

TRANSITIONS = {
    "NEW": {"REVIEWING"},
    "REVIEWING": {"NEW", "PURSUE", "HOLD", "PASS"},
    "PURSUE": {"REVIEWING"},
    "HOLD": {"REVIEWING"},
    "PASS": {"REVIEWING"},
}

SCHEMA = """
CREATE TABLE IF NOT EXISTS deals (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id          TEXT UNIQUE,
    name             TEXT NOT NULL,
    asset_type       TEXT NOT NULL,
    location         TEXT NOT NULL,
    source           TEXT NOT NULL DEFAULT '',
    inputs_json      TEXT NOT NULL,
    underwriting_json TEXT NOT NULL,
    contact_json     TEXT NOT NULL,
    status           TEXT NOT NULL DEFAULT 'NEW',
    artifact_path    TEXT,
    created_at       TEXT NOT NULL,
    updated_at       TEXT NOT NULL
)
"""

# PostgreSQL equivalents. Same tables and columns; SERIAL replaces
# INTEGER PRIMARY KEY AUTOINCREMENT. CREATE TABLE IF NOT EXISTS and the
# TEXT/UNIQUE/DEFAULT clauses are valid in both dialects.
PG_SCHEMA = """
CREATE TABLE IF NOT EXISTS deals (
    id               SERIAL PRIMARY KEY,
    deal_id          TEXT UNIQUE,
    name             TEXT NOT NULL,
    asset_type       TEXT NOT NULL,
    location         TEXT NOT NULL,
    source           TEXT NOT NULL DEFAULT '',
    inputs_json      TEXT NOT NULL,
    underwriting_json TEXT NOT NULL,
    contact_json     TEXT NOT NULL,
    status           TEXT NOT NULL DEFAULT 'NEW',
    artifact_path    TEXT,
    created_at       TEXT NOT NULL,
    updated_at       TEXT NOT NULL
)
"""

PG_DD_ITEMS_SCHEMA = """
CREATE TABLE IF NOT EXISTS dd_items (
    id        SERIAL PRIMARY KEY,
    deal_id   TEXT NOT NULL,
    category  TEXT NOT NULL,
    item_key  TEXT NOT NULL,
    label     TEXT NOT NULL,
    status    TEXT NOT NULL DEFAULT 'not_started',
    notes     TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (deal_id, item_key)
)
"""

PG_DD_DOCUMENTS_SCHEMA = """
CREATE TABLE IF NOT EXISTS dd_documents (
    id          SERIAL PRIMARY KEY,
    deal_id     TEXT NOT NULL,
    item_key    TEXT NOT NULL,
    filename    TEXT NOT NULL,
    stored_path TEXT NOT NULL,
    note        TEXT NOT NULL DEFAULT '',
    uploaded_at TEXT NOT NULL
)
"""

# Charter-analytics tables. Additive: deal records, seed data, and existing
# tables are untouched. SERIAL replaces INTEGER PRIMARY KEY AUTOINCREMENT
# for PostgreSQL; CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT EXISTS
# are valid in both dialects.
ANALYTICS_SCHEMA = """
CREATE TABLE IF NOT EXISTS evidence (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id    TEXT NOT NULL,
    type       TEXT NOT NULL,
    source     TEXT NOT NULL DEFAULT '',
    content    TEXT NOT NULL,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_evidence_deal ON evidence(deal_id);
CREATE TABLE IF NOT EXISTS perspectives (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id       TEXT NOT NULL,
    lens          TEXT NOT NULL,
    analysis_json TEXT NOT NULL,
    created_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_perspectives_deal ON perspectives(deal_id);
CREATE TABLE IF NOT EXISTS scenarios (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id      TEXT NOT NULL,
    name         TEXT NOT NULL,
    overrides_json TEXT NOT NULL,
    results_json TEXT NOT NULL,
    created_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_scenarios_deal ON scenarios(deal_id);
CREATE TABLE IF NOT EXISTS simulations (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id       TEXT NOT NULL,
    ranges_json   TEXT NOT NULL,
    n             INTEGER NOT NULL,
    seed          INTEGER NOT NULL,
    summary_json  TEXT NOT NULL,
    created_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_simulations_deal ON simulations(deal_id);
CREATE TABLE IF NOT EXISTS theses (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id               TEXT NOT NULL,
    thesis                TEXT NOT NULL,
    key_assumptions_json  TEXT NOT NULL,
    expected_outcome      TEXT NOT NULL DEFAULT '',
    created_at            TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_theses_deal ON theses(deal_id);
CREATE TABLE IF NOT EXISTS outcomes (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id               TEXT NOT NULL,
    thesis_agreement      TEXT NOT NULL,
    outcome_summary       TEXT NOT NULL,
    actual_metrics_json   TEXT NOT NULL,
    created_at            TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_outcomes_deal ON outcomes(deal_id);
"""

PG_ANALYTICS_SCHEMA = """
CREATE TABLE IF NOT EXISTS evidence (
    id         SERIAL PRIMARY KEY,
    deal_id    TEXT NOT NULL,
    type       TEXT NOT NULL,
    source     TEXT NOT NULL DEFAULT '',
    content    TEXT NOT NULL,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_evidence_deal ON evidence(deal_id);
CREATE TABLE IF NOT EXISTS perspectives (
    id            SERIAL PRIMARY KEY,
    deal_id       TEXT NOT NULL,
    lens          TEXT NOT NULL,
    analysis_json TEXT NOT NULL,
    created_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_perspectives_deal ON perspectives(deal_id);
CREATE TABLE IF NOT EXISTS scenarios (
    id           SERIAL PRIMARY KEY,
    deal_id      TEXT NOT NULL,
    name         TEXT NOT NULL,
    overrides_json TEXT NOT NULL,
    results_json TEXT NOT NULL,
    created_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_scenarios_deal ON scenarios(deal_id);
CREATE TABLE IF NOT EXISTS simulations (
    id            SERIAL PRIMARY KEY,
    deal_id       TEXT NOT NULL,
    ranges_json   TEXT NOT NULL,
    n             INTEGER NOT NULL,
    seed          INTEGER NOT NULL,
    summary_json  TEXT NOT NULL,
    created_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_simulations_deal ON simulations(deal_id);
CREATE TABLE IF NOT EXISTS theses (
    id                    SERIAL PRIMARY KEY,
    deal_id               TEXT NOT NULL,
    thesis                TEXT NOT NULL,
    key_assumptions_json  TEXT NOT NULL,
    expected_outcome      TEXT NOT NULL DEFAULT '',
    created_at            TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_theses_deal ON theses(deal_id);
CREATE TABLE IF NOT EXISTS outcomes (
    id                    SERIAL PRIMARY KEY,
    deal_id               TEXT NOT NULL,
    thesis_agreement      TEXT NOT NULL,
    outcome_summary       TEXT NOT NULL,
    actual_metrics_json   TEXT NOT NULL,
    created_at            TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_outcomes_deal ON outcomes(deal_id);
"""


def _database_url():
    return os.environ.get("DATABASE_URL", "").strip()


def _using_postgres(path=None):
    """True when this operation should go to PostgreSQL.

    An explicit `path` always means local SQLite (tests, CLI overrides);
    otherwise DATABASE_URL selects Postgres.
    """
    return path is None and bool(_database_url())


def _q(sql, pg):
    """Translate `?` placeholders to `%s` for PostgreSQL.

    Safe because no SQL string in this module contains a literal `?`
    or `%` outside of parameter placeholders.
    """
    return sql.replace("?", "%s") if pg else sql


def _ensure_source_column(conn, pg):
    """Add the `source` column to databases created before it existed."""
    if pg:
        rows = conn.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name = 'deals'").fetchall()
        cols = [r["column_name"] for r in rows]
    else:
        cols = [r[1] for r in conn.execute("PRAGMA table_info(deals)").fetchall()]
    if "source" not in cols:
        conn.execute("ALTER TABLE deals ADD COLUMN source TEXT NOT NULL DEFAULT ''")


def _db_path(path=None):
    return path or os.environ.get("DEALFLOW_DB", DEFAULT_DB)


def _execute_ddl(conn, schema, pg):
    """Execute a multi-statement DDL string one statement at a time.

    sqlite3's execute() rejects strings containing more than one
    statement; splitting on ';' works for both dialects (no DDL here
    contains a literal semicolon).
    """
    for stmt in schema.split(";"):
        stmt = stmt.strip()
        if stmt:
            conn.execute(_q(stmt, pg))


def _connect(path=None):
    pg = _using_postgres(path)
    if pg:
        if psycopg is None:
            raise RuntimeError(
                "DATABASE_URL is set but the 'psycopg' package is not installed.")
        conn = psycopg.connect(_database_url(), row_factory=dict_row)
        conn.execute(PG_SCHEMA)
        conn.execute(PG_DD_ITEMS_SCHEMA)
        conn.execute(PG_DD_DOCUMENTS_SCHEMA)
        _execute_ddl(conn, PG_ANALYTICS_SCHEMA, pg=True)
        conn.commit()
        _ensure_source_column(conn, pg=True)
        return conn
    conn = sqlite3.connect(_db_path(path))
    conn.row_factory = sqlite3.Row
    conn.execute(SCHEMA)
    conn.execute(DD_ITEMS_SCHEMA)
    conn.execute(DD_DOCUMENTS_SCHEMA)
    _execute_ddl(conn, ANALYTICS_SCHEMA, pg=False)
    conn.commit()
    _ensure_source_column(conn, pg=False)
    return conn


def _now_iso():
    return datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")


def _now_precise():
    """Microsecond-precision timestamp for the analytics tables.

    The observer matches outcomes to theses by strict "recorded after"
    ordering; second precision would tie when a thesis and its outcome
    are recorded in the same second.
    """
    return datetime.datetime.now(datetime.timezone.utc).isoformat()


def _row_to_deal(row):
    keys = row.keys()
    return {
        "deal_id": row["deal_id"],
        "name": row["name"],
        "asset_type": row["asset_type"],
        "location": row["location"],
        "source": row["source"] if "source" in keys else "",
        "inputs": json.loads(row["inputs_json"]),
        "underwriting": json.loads(row["underwriting_json"]),
        "contact": json.loads(row["contact_json"]),
        "status": row["status"],
        "artifact_path": row["artifact_path"],
        "created_at": row["created_at"],
        "updated_at": row["updated_at"],
    }


def submit_deal(raw, path=None):
    """Validate, persist, and underwrite a deal. Returns the new Deal ID.

    Raises ValueError with a readable message when validation fails.
    This is the single real submission path for the web app and the CLI.
    """
    cleaned, errors = validation.validate(raw)
    if errors:
        raise ValueError("; ".join(e["message"] for e in errors))

    inputs = {f: cleaned.get(f) for f in validation.INPUT_FIELDS}
    contact = {f: cleaned.get(f, "") for f in validation.CONTACT_FIELDS}
    extras = {f: cleaned.get(f, "") for f in validation.EXTRA_FIELDS}

    pg = _using_postgres(path)
    now = _now_iso()
    conn = _connect(path)
    try:
        insert_sql = _q(
            """INSERT INTO deals
               (name, asset_type, location, source, inputs_json, underwriting_json,
                contact_json, status, created_at, updated_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, 'NEW', ?, ?)""", pg)
        params = (cleaned["name"], cleaned["asset_type"], cleaned["location"],
                  cleaned.get("source", ""),
                  json.dumps(inputs), json.dumps({}),
                  json.dumps({**contact, **extras}), now, now)
        if pg:
            cur = conn.execute(insert_sql + " RETURNING id", params)
            row_id = cur.fetchone()["id"]
        else:
            cur = conn.execute(insert_sql, params)
            row_id = cur.lastrowid
        deal_id = "AT-%s-%06d" % (datetime.datetime.now().year, row_id)

        result = underwriting.calculate(inputs)

        conn.execute(
            _q("UPDATE deals SET deal_id = ?, underwriting_json = ?, updated_at = ? "
               "WHERE id = ?", pg),
            (deal_id, json.dumps(result), _now_iso(), row_id),
        )
        seed_dd_checklist(deal_id, conn)
        conn.commit()
    finally:
        conn.close()
    return deal_id


def get_deal(deal_id, path=None):
    """Return the canonical deal record dict, or None if unknown."""
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        row = conn.execute(
            _q("SELECT * FROM deals WHERE deal_id = ?", pg), (deal_id,)).fetchone()
    finally:
        conn.close()
    return _row_to_deal(row) if row else None


def list_deals(status=None, path=None):
    """Newest-first list of deal records, optionally filtered by status."""
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        if status:
            rows = conn.execute(
                _q("SELECT * FROM deals WHERE status = ? ORDER BY id DESC", pg),
                (status,)).fetchall()
        else:
            rows = conn.execute("SELECT * FROM deals ORDER BY id DESC").fetchall()
    finally:
        conn.close()
    return [_row_to_deal(r) for r in rows]


def set_status(deal_id, new_status, path=None):
    """Human-controlled status change. Enforces the documented transitions."""
    if new_status not in STATUSES:
        raise ValueError("Unknown status: %r" % (new_status,))
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        row = conn.execute(
            _q("SELECT status FROM deals WHERE deal_id = ?", pg),
            (deal_id,)).fetchone()
        if not row:
            raise ValueError("Unknown deal: %r" % (deal_id,))
        current = row["status"]
        if new_status != current and new_status not in TRANSITIONS[current]:
            raise ValueError(
                "Status change %s -> %s is not allowed." % (current, new_status))
        conn.execute(
            _q("UPDATE deals SET status = ?, updated_at = ? WHERE deal_id = ?",
               pg),
            (new_status, _now_iso(), deal_id))
        conn.commit()
    finally:
        conn.close()
    return new_status


def set_artifact(deal_id, artifact_path, path=None):
    """Record the generated Excel artifact reference on the deal."""
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        conn.execute(
            _q("UPDATE deals SET artifact_path = ?, updated_at = ? WHERE deal_id = ?",
               pg),
            (artifact_path, _now_iso(), deal_id))
        conn.commit()
    finally:
        conn.close()


# ---------- due diligence ----------

def seed_dd_checklist(deal_id, conn=None, path=None):
    """Seed the standard DD checklist for a deal. Idempotent: existing
    items are left untouched, so backfills never duplicate or reset work."""
    own = conn is None
    pg = _using_postgres(path)
    if own:
        conn = _connect(path)
    try:
        now = _now_iso()
        base = ("INSERT {ignore}INTO dd_items "
                "(deal_id, category, item_key, label, status, notes, "
                "created_at, updated_at) "
                "VALUES (?, ?, ?, ?, 'not_started', '', ?, ?)")
        if pg:
            sql = _q(base.format(ignore=""), pg) + \
                " ON CONFLICT (deal_id, item_key) DO NOTHING"
        else:
            sql = base.format(ignore="OR IGNORE ")
        for category, item_key, label in DD_CHECKLIST:
            conn.execute(sql, (deal_id, category, item_key, label, now, now))
        if own:
            conn.commit()
    finally:
        if own:
            conn.close()


def backfill_dd_checklist(path=None):
    """Seed the checklist for every deal that does not have it yet.
    Returns the number of deals seeded."""
    conn = _connect(path)
    try:
        rows = conn.execute("SELECT deal_id FROM deals").fetchall()
        for row in rows:
            seed_dd_checklist(row["deal_id"], conn)
        conn.commit()
        return len(rows)
    finally:
        conn.close()


def _dd_item_row(row):
    return {
        "id": row["id"],
        "deal_id": row["deal_id"],
        "category": row["category"],
        "item_key": row["item_key"],
        "label": row["label"],
        "status": row["status"],
        "notes": row["notes"],
        "created_at": row["created_at"],
        "updated_at": row["updated_at"],
    }


def list_dd_items(deal_id, path=None):
    """Checklist items for a deal, in checklist order."""
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        rows = conn.execute(
            _q("SELECT * FROM dd_items WHERE deal_id = ? ORDER BY id", pg),
            (deal_id,)).fetchall()
    finally:
        conn.close()
    return [_dd_item_row(r) for r in rows]


def dd_item_exists(deal_id, item_key, path=None):
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        row = conn.execute(
            _q("SELECT id FROM dd_items WHERE deal_id = ? AND item_key = ?",
               pg),
            (deal_id, item_key)).fetchone()
    finally:
        conn.close()
    return row is not None


def set_dd_status(deal_id, item_key, status, path=None):
    """Human-controlled DD item status. Any transition is allowed; DD
    workflow state is tracked, not decided, by the engine."""
    if status not in DD_STATUSES:
        raise ValueError("Unknown DD status: %r" % (status,))
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        cur = conn.execute(
            _q("UPDATE dd_items SET status = ?, updated_at = ? "
               "WHERE deal_id = ? AND item_key = ?", pg),
            (status, _now_iso(), deal_id, item_key))
        if cur.rowcount == 0:
            raise ValueError("Unknown DD item: %r" % (item_key,))
        conn.commit()
    finally:
        conn.close()
    return status


def set_dd_notes(deal_id, item_key, notes, path=None):
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        cur = conn.execute(
            _q("UPDATE dd_items SET notes = ?, updated_at = ? "
               "WHERE deal_id = ? AND item_key = ?", pg),
            (notes or "", _now_iso(), deal_id, item_key))
        if cur.rowcount == 0:
            raise ValueError("Unknown DD item: %r" % (item_key,))
        conn.commit()
    finally:
        conn.close()


def add_dd_document(deal_id, item_key, filename, stored_path, note="",
                    path=None):
    """Record an uploaded DD document. Returns the document id."""
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        insert_sql = _q(
            """INSERT INTO dd_documents
               (deal_id, item_key, filename, stored_path, note, uploaded_at)
               VALUES (?, ?, ?, ?, ?, ?)""", pg)
        params = (deal_id, item_key, filename, stored_path, note or "",
                  _now_iso())
        if pg:
            cur = conn.execute(insert_sql + " RETURNING id", params)
            doc_id = cur.fetchone()["id"]
        else:
            cur = conn.execute(insert_sql, params)
            doc_id = cur.lastrowid
        conn.commit()
    finally:
        conn.close()
    return doc_id


def _dd_doc_row(row):
    return {
        "id": row["id"],
        "deal_id": row["deal_id"],
        "item_key": row["item_key"],
        "filename": row["filename"],
        "stored_path": row["stored_path"],
        "note": row["note"],
        "uploaded_at": row["uploaded_at"],
    }


def list_dd_documents(deal_id, item_key=None, path=None):
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        if item_key:
            rows = conn.execute(
                _q("SELECT * FROM dd_documents WHERE deal_id = ? AND item_key = ? "
                   "ORDER BY id", pg),
                (deal_id, item_key)).fetchall()
        else:
            rows = conn.execute(
                _q("SELECT * FROM dd_documents WHERE deal_id = ? ORDER BY id",
                   pg),
                (deal_id,)).fetchall()
    finally:
        conn.close()
    return [_dd_doc_row(r) for r in rows]


def get_dd_document(doc_id, path=None):
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        row = conn.execute(
            _q("SELECT * FROM dd_documents WHERE id = ?", pg),
            (doc_id,)).fetchone()
    finally:
        conn.close()
    return _dd_doc_row(row) if row else None


def dd_progress(deal_id, path=None):
    """Return (cleared_count, total_count) for a deal's DD checklist."""
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        row = conn.execute(
            _q("SELECT COUNT(*) AS total, "
               "SUM(CASE WHEN status = 'cleared' THEN 1 ELSE 0 END) AS cleared "
               "FROM dd_items WHERE deal_id = ?", pg),
            (deal_id,)).fetchone()
    finally:
        conn.close()
    return (row["cleared"] or 0, row["total"] or 0)


def dd_progress_all(path=None):
    """Return {deal_id: (cleared, total)} for every deal with a checklist."""
    conn = _connect(path)
    try:
        rows = conn.execute(
            "SELECT deal_id, COUNT(*) AS total, "
            "SUM(CASE WHEN status = 'cleared' THEN 1 ELSE 0 END) AS cleared "
            "FROM dd_items GROUP BY deal_id").fetchall()
    finally:
        conn.close()
    return {r["deal_id"]: (r["cleared"] or 0, r["total"] or 0) for r in rows}


# ---------------------------------------------------------------------------
# Charter analytics: evidence log
# ---------------------------------------------------------------------------

def _insert_returning_id(conn, pg, sql, params):
    """Run an INSERT and return the new row id on either dialect."""
    if pg:
        row = conn.execute(_q(sql + " RETURNING id", pg=True), params).fetchone()
        new_id = row["id"]
    else:
        cur = conn.execute(sql, params)
        new_id = cur.lastrowid
    conn.commit()
    return new_id


def add_evidence(deal_id, evidence_type, content, source="", path=None):
    """Append one typed evidence item to a deal's evidence log."""
    evidence_mod.validate_evidence(evidence_type, content)
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        new_id = _insert_returning_id(
            conn, pg,
            "INSERT INTO evidence (deal_id, type, source, content, created_at) "
            "VALUES (?, ?, ?, ?, ?)",
            (deal_id, evidence_type, source or "", content, _now_precise()))
    finally:
        conn.close()
    return new_id


def _evidence_row(row):
    return {
        "id": row["id"],
        "deal_id": row["deal_id"],
        "type": row["type"],
        "source": row["source"],
        "content": row["content"],
        "created_at": row["created_at"],
    }


def list_evidence(deal_id, path=None):
    """Return a deal's evidence log, oldest first."""
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        rows = conn.execute(
            _q("SELECT * FROM evidence WHERE deal_id = ? ORDER BY id", pg),
            (deal_id,)).fetchall()
    finally:
        conn.close()
    return [_evidence_row(r) for r in rows]


# ---------------------------------------------------------------------------
# Charter analytics: perspectives
# ---------------------------------------------------------------------------

def save_perspectives(deal_id, analyses, path=None):
    """Store one analysis dict per lens; lenses are never merged.

    ``analyses`` is the ``analyze_deal()`` output: {lens: analysis_dict}.
    History is append-only: a second run adds rows, it never rewrites.
    Returns the list of new row ids.
    """
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        new_ids = []
        for lens, analysis in analyses.items():
            new_ids.append(_insert_returning_id(
                conn, pg,
                "INSERT INTO perspectives (deal_id, lens, analysis_json, created_at) "
                "VALUES (?, ?, ?, ?)",
                (deal_id, lens, json.dumps(analysis), _now_precise())))
    finally:
        conn.close()
    return new_ids


def _perspective_row(row):
    return {
        "id": row["id"],
        "deal_id": row["deal_id"],
        "lens": row["lens"],
        "analysis": json.loads(row["analysis_json"]),
        "created_at": row["created_at"],
    }


def list_perspectives(deal_id, path=None):
    """Return all stored lens analyses for a deal, oldest first."""
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        rows = conn.execute(
            _q("SELECT * FROM perspectives WHERE deal_id = ? ORDER BY id", pg),
            (deal_id,)).fetchall()
    finally:
        conn.close()
    return [_perspective_row(r) for r in rows]


# ---------------------------------------------------------------------------
# Charter analytics: scenarios and simulations
# ---------------------------------------------------------------------------

def save_scenarios(deal_id, name, overrides, results, path=None):
    """Store one scenario run (overrides + re-underwritten results)."""
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        new_id = _insert_returning_id(
            conn, pg,
            "INSERT INTO scenarios (deal_id, name, overrides_json, results_json, created_at) "
            "VALUES (?, ?, ?, ?, ?)",
            (deal_id, name, json.dumps(overrides), json.dumps(results), _now_precise()))
    finally:
        conn.close()
    return new_id


def _scenario_row(row):
    return {
        "id": row["id"],
        "deal_id": row["deal_id"],
        "name": row["name"],
        "overrides": json.loads(row["overrides_json"]),
        "results": json.loads(row["results_json"]),
        "created_at": row["created_at"],
    }


def list_scenarios(deal_id, path=None):
    """Return all stored scenario runs for a deal, oldest first."""
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        rows = conn.execute(
            _q("SELECT * FROM scenarios WHERE deal_id = ? ORDER BY id", pg),
            (deal_id,)).fetchall()
    finally:
        conn.close()
    return [_scenario_row(r) for r in rows]


def save_simulation(deal_id, ranges, n, seed, summary, path=None):
    """Store one Monte Carlo run's configuration and summary."""
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        new_id = _insert_returning_id(
            conn, pg,
            "INSERT INTO simulations (deal_id, ranges_json, n, seed, summary_json, created_at) "
            "VALUES (?, ?, ?, ?, ?, ?)",
            (deal_id, json.dumps(ranges), n, seed, json.dumps(summary), _now_precise()))
    finally:
        conn.close()
    return new_id


def _simulation_row(row):
    return {
        "id": row["id"],
        "deal_id": row["deal_id"],
        "ranges": json.loads(row["ranges_json"]),
        "n": row["n"],
        "seed": row["seed"],
        "summary": json.loads(row["summary_json"]),
        "created_at": row["created_at"],
    }


def list_simulations(deal_id, path=None):
    """Return all stored simulation runs for a deal, oldest first."""
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        rows = conn.execute(
            _q("SELECT * FROM simulations WHERE deal_id = ? ORDER BY id", pg),
            (deal_id,)).fetchall()
    finally:
        conn.close()
    return [_simulation_row(r) for r in rows]


# ---------------------------------------------------------------------------
# Charter analytics: decision journal
# ---------------------------------------------------------------------------

def record_thesis(deal_id, thesis, key_assumptions=None, expected_outcome="", path=None):
    """Record a falsifiable thesis for a deal.

    Only allowed while the deal is in PURSUE status (see journal.py).
    Theses are immutable: there is no edit path, only later outcomes.
    Raises KeyError for an unknown deal, ValueError for any other status.
    """
    if not thesis or not str(thesis).strip():
        raise ValueError("Thesis text must not be empty.")
    deal = get_deal(deal_id, path)
    journal_mod.check_thesis_allowed(deal, deal_id)
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        new_id = _insert_returning_id(
            conn, pg,
            "INSERT INTO theses (deal_id, thesis, key_assumptions_json, expected_outcome, created_at) "
            "VALUES (?, ?, ?, ?, ?)",
            (deal_id, thesis, json.dumps(list(key_assumptions or [])),
             expected_outcome or "", _now_precise()))
    finally:
        conn.close()
    return new_id


def _thesis_row(row):
    return {
        "id": row["id"],
        "deal_id": row["deal_id"],
        "thesis": row["thesis"],
        "key_assumptions": json.loads(row["key_assumptions_json"]),
        "expected_outcome": row["expected_outcome"],
        "created_at": row["created_at"],
    }


def list_theses(deal_id, path=None):
    """Return all theses for a deal, oldest first."""
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        rows = conn.execute(
            _q("SELECT * FROM theses WHERE deal_id = ? ORDER BY id", pg),
            (deal_id,)).fetchall()
    finally:
        conn.close()
    return [_thesis_row(r) for r in rows]


def record_outcome(deal_id, thesis_agreement, outcome_summary, actual_metrics=None, path=None):
    """Record what actually happened for a deal.

    ``thesis_agreement`` must be "agree", "disagree", or "unclear".
    Outcomes do not edit theses; the observer view compares them in order.
    """
    if thesis_agreement not in ("agree", "disagree", "unclear"):
        raise ValueError(
            f"thesis_agreement must be 'agree', 'disagree', or 'unclear', got {thesis_agreement!r}.")
    if not outcome_summary or not str(outcome_summary).strip():
        raise ValueError("Outcome summary must not be empty.")
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        new_id = _insert_returning_id(
            conn, pg,
            "INSERT INTO outcomes (deal_id, thesis_agreement, outcome_summary, actual_metrics_json, created_at) "
            "VALUES (?, ?, ?, ?, ?)",
            (deal_id, thesis_agreement, outcome_summary,
             json.dumps(dict(actual_metrics or {})), _now_precise()))
    finally:
        conn.close()
    return new_id


def _outcome_row(row):
    return {
        "id": row["id"],
        "deal_id": row["deal_id"],
        "thesis_agreement": row["thesis_agreement"],
        "outcome_summary": row["outcome_summary"],
        "actual_metrics": json.loads(row["actual_metrics_json"]),
        "created_at": row["created_at"],
    }


def list_outcomes(deal_id, path=None):
    """Return all outcomes for a deal, oldest first."""
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        rows = conn.execute(
            _q("SELECT * FROM outcomes WHERE deal_id = ? ORDER BY id", pg),
            (deal_id,)).fetchall()
    finally:
        conn.close()
    return [_outcome_row(r) for r in rows]


def _all_theses(path=None):
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        rows = conn.execute("SELECT * FROM theses ORDER BY id").fetchall()
    finally:
        conn.close()
    return [_thesis_row(r) for r in rows]


def _all_outcomes(path=None):
    pg = _using_postgres(path)
    conn = _connect(path)
    try:
        rows = conn.execute("SELECT * FROM outcomes ORDER BY id").fetchall()
    finally:
        conn.close()
    return [_outcome_row(r) for r in rows]


def observer_summary(path=None):
    """Build the observer audit view over the whole decision journal.

    Compares each thesis against the first later outcome for the same deal,
    in order; outcomes with no preceding thesis are listed as unmatched.
    The observer judges the journal's calibration, never the deals.
    """
    theses = _all_theses(path)
    outcomes = _all_outcomes(path)
    deals_by_id: dict = {}
    for entry in theses + outcomes:
        deal_id = entry["deal_id"]
        if deal_id not in deals_by_id:
            deal = get_deal(deal_id, path)
            deals_by_id[deal_id] = {
                "name": deal["name"] if deal else None,
                "status": deal["status"] if deal else None,
            }
    return journal_mod.build_observer_summary(theses, outcomes, deals_by_id)
