"""AletheiaTelos DealFlow Engine — canonical deal record persistence.

One SQLite table (`deals`). The record is the canonical source of truth:

  identity          deal_id, name, asset_type, location
  original_inputs   the 11 validated financial inputs, exactly as submitted
  underwriting      deterministic results with provenance (from underwriting.py)
  workflow          status, created_at, updated_at, artifact_reference
  contact           name / email / phone as submitted

Rules:
  - Deal IDs are generated by the application as AT-YYYY-NNNNNN from the
    database row id. They never depend on property data.
  - Original inputs are never overwritten by calculations; underwriting
    results live in their own JSON column.
  - Missing information stays explicit (None in inputs, "unavailable" in
    underwriting).
  - Status transitions are human-controlled: NEW -> REVIEWING -> PURSUE/HOLD/PASS,
    with reopening back to REVIEWING allowed. Terminal states cannot jump
    arbitrarily.

The submission path used by the web app AND the import CLI is submit_deal():
  raw intake dict -> validation -> record -> underwriting -> stored record.
"""

import datetime
import json
import os
import sqlite3

import underwriting
import validation

REPO_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_DB = os.path.join(REPO_DIR, "dealflow.db")

STATUSES = ("NEW", "REVIEWING", "PURSUE", "HOLD", "PASS")

# ---------- due diligence ----------

DD_STATUSES = ("not_started", "requested", "received", "in_review",
               "cleared", "waived", "issue")

# (category, item_key, label) — the standard CRE checklist seeded for every deal.
DD_CHECKLIST = [
    ("Legal / Title", "purchase_agreement", "Purchase agreement"),
    ("Legal / Title", "title_commitment", "Title commitment"),
    ("Legal / Title", "title_exceptions", "Title exceptions reviewed"),
    ("Legal / Title", "survey", "Survey"),
    ("Legal / Title", "zoning_verification", "Zoning verification"),
    ("Financial", "rent_roll", "Rent roll"),
    ("Financial", "leases", "Leases"),
    ("Financial", "operating_statements", "12-month operating statements"),
    ("Financial", "tax_returns", "Tax returns"),
    ("Financial", "estoppels", "Estoppel certificates"),
    ("Physical / Environmental", "inspection", "Property inspection"),
    ("Physical / Environmental", "phase_i", "Environmental Phase I"),
    ("Physical / Environmental", "major_systems", "Major systems (roof / HVAC)"),
    ("Insurance / Compliance", "insurance_quotes", "Insurance quotes"),
    ("Insurance / Compliance", "flood_zone", "Flood zone determination"),
    ("Insurance / Compliance", "permits_co", "Permits / certificate of occupancy"),
    ("Association", "hoa_docs", "HOA / condo docs (waive if not applicable)"),
    ("Financing", "loan_term_sheet", "Loan term sheet"),
    ("Financing", "appraisal", "Appraisal"),
]

DD_CATEGORIES = []
for _cat, _key, _label in DD_CHECKLIST:
    if _cat not in DD_CATEGORIES:
        DD_CATEGORIES.append(_cat)
del _cat, _key, _label

DD_ITEMS_SCHEMA = """
CREATE TABLE IF NOT EXISTS dd_items (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id   TEXT NOT NULL,
    category  TEXT NOT NULL,
    item_key  TEXT NOT NULL,
    label     TEXT NOT NULL,
    status    TEXT NOT NULL DEFAULT 'not_started',
    notes     TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (deal_id, item_key)
)
"""

DD_DOCUMENTS_SCHEMA = """
CREATE TABLE IF NOT EXISTS dd_documents (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id     TEXT NOT NULL,
    item_key    TEXT NOT NULL,
    filename    TEXT NOT NULL,
    stored_path TEXT NOT NULL,
    note        TEXT NOT NULL DEFAULT '',
    uploaded_at TEXT NOT NULL
)
"""

TRANSITIONS = {
    "NEW": {"REVIEWING"},
    "REVIEWING": {"NEW", "PURSUE", "HOLD", "PASS"},
    "PURSUE": {"REVIEWING"},
    "HOLD": {"REVIEWING"},
    "PASS": {"REVIEWING"},
}

SCHEMA = """
CREATE TABLE IF NOT EXISTS deals (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id          TEXT UNIQUE,
    name             TEXT NOT NULL,
    asset_type       TEXT NOT NULL,
    location         TEXT NOT NULL,
    source           TEXT NOT NULL DEFAULT '',
    inputs_json      TEXT NOT NULL,
    underwriting_json TEXT NOT NULL,
    contact_json     TEXT NOT NULL,
    status           TEXT NOT NULL DEFAULT 'NEW',
    artifact_path    TEXT,
    created_at       TEXT NOT NULL,
    updated_at       TEXT NOT NULL
)
"""


def _ensure_source_column(conn):
    """Add the `source` column to databases created before it existed."""
    cols = [r[1] for r in conn.execute("PRAGMA table_info(deals)").fetchall()]
    if "source" not in cols:
        conn.execute("ALTER TABLE deals ADD COLUMN source TEXT NOT NULL DEFAULT ''")
        conn.commit()


def _db_path(path=None):
    return path or os.environ.get("DEALFLOW_DB", DEFAULT_DB)


def _connect(path=None):
    conn = sqlite3.connect(_db_path(path))
    conn.row_factory = sqlite3.Row
    conn.execute(SCHEMA)
    conn.execute(DD_ITEMS_SCHEMA)
    conn.execute(DD_DOCUMENTS_SCHEMA)
    conn.commit()
    _ensure_source_column(conn)
    return conn


def _now_iso():
    return datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")


def _row_to_deal(row):
    keys = row.keys()
    return {
        "deal_id": row["deal_id"],
        "name": row["name"],
        "asset_type": row["asset_type"],
        "location": row["location"],
        "source": row["source"] if "source" in keys else "",
        "inputs": json.loads(row["inputs_json"]),
        "underwriting": json.loads(row["underwriting_json"]),
        "contact": json.loads(row["contact_json"]),
        "status": row["status"],
        "artifact_path": row["artifact_path"],
        "created_at": row["created_at"],
        "updated_at": row["updated_at"],
    }


def submit_deal(raw, path=None):
    """Validate, persist, and underwrite a deal. Returns the new Deal ID.

    Raises ValueError with a readable message when validation fails.
    This is the single real submission path for the web app and the CLI.
    """
    cleaned, errors = validation.validate(raw)
    if errors:
        raise ValueError("; ".join(e["message"] for e in errors))

    inputs = {f: cleaned.get(f) for f in validation.INPUT_FIELDS}
    contact = {f: cleaned.get(f, "") for f in validation.CONTACT_FIELDS}
    extras = {f: cleaned.get(f, "") for f in validation.EXTRA_FIELDS}

    now = _now_iso()
    conn = _connect(path)
    try:
        cur = conn.execute(
            """INSERT INTO deals
               (name, asset_type, location, source, inputs_json, underwriting_json,
                contact_json, status, created_at, updated_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, 'NEW', ?, ?)""",
            (cleaned["name"], cleaned["asset_type"], cleaned["location"],
             cleaned.get("source", ""),
             json.dumps(inputs), json.dumps({}),
             json.dumps({**contact, **extras}), now, now),
        )
        row_id = cur.lastrowid
        deal_id = "AT-%s-%06d" % (datetime.datetime.now().year, row_id)

        result = underwriting.calculate(inputs)

        conn.execute(
            "UPDATE deals SET deal_id = ?, underwriting_json = ?, updated_at = ? "
            "WHERE id = ?",
            (deal_id, json.dumps(result), _now_iso(), row_id),
        )
        seed_dd_checklist(deal_id, conn)
        conn.commit()
    finally:
        conn.close()
    return deal_id


def get_deal(deal_id, path=None):
    """Return the canonical deal record dict, or None if unknown."""
    conn = _connect(path)
    try:
        row = conn.execute(
            "SELECT * FROM deals WHERE deal_id = ?", (deal_id,)).fetchone()
    finally:
        conn.close()
    return _row_to_deal(row) if row else None


def list_deals(status=None, path=None):
    """Newest-first list of deal records, optionally filtered by status."""
    conn = _connect(path)
    try:
        if status:
            rows = conn.execute(
                "SELECT * FROM deals WHERE status = ? ORDER BY id DESC",
                (status,)).fetchall()
        else:
            rows = conn.execute("SELECT * FROM deals ORDER BY id DESC").fetchall()
    finally:
        conn.close()
    return [_row_to_deal(r) for r in rows]


def set_status(deal_id, new_status, path=None):
    """Human-controlled status change. Enforces the documented transitions."""
    if new_status not in STATUSES:
        raise ValueError("Unknown status: %r" % (new_status,))
    conn = _connect(path)
    try:
        row = conn.execute(
            "SELECT status FROM deals WHERE deal_id = ?", (deal_id,)).fetchone()
        if not row:
            raise ValueError("Unknown deal: %r" % (deal_id,))
        current = row["status"]
        if new_status != current and new_status not in TRANSITIONS[current]:
            raise ValueError(
                "Status change %s -> %s is not allowed." % (current, new_status))
        conn.execute(
            "UPDATE deals SET status = ?, updated_at = ? WHERE deal_id = ?",
            (new_status, _now_iso(), deal_id))
        conn.commit()
    finally:
        conn.close()
    return new_status


def set_artifact(deal_id, artifact_path, path=None):
    """Record the generated Excel artifact reference on the deal."""
    conn = _connect(path)
    try:
        conn.execute(
            "UPDATE deals SET artifact_path = ?, updated_at = ? WHERE deal_id = ?",
            (artifact_path, _now_iso(), deal_id))
        conn.commit()
    finally:
        conn.close()


# ---------- due diligence ----------

def seed_dd_checklist(deal_id, conn=None, path=None):
    """Seed the standard DD checklist for a deal. Idempotent: existing
    items are left untouched, so backfills never duplicate or reset work."""
    own = conn is None
    if own:
        conn = _connect(path)
    try:
        now = _now_iso()
        for category, item_key, label in DD_CHECKLIST:
            conn.execute(
                """INSERT OR IGNORE INTO dd_items
                   (deal_id, category, item_key, label, status, notes,
                    created_at, updated_at)
                   VALUES (?, ?, ?, ?, 'not_started', '', ?, ?)""",
                (deal_id, category, item_key, label, now, now),
            )
        if own:
            conn.commit()
    finally:
        if own:
            conn.close()


def backfill_dd_checklist(path=None):
    """Seed the checklist for every deal that does not have it yet.
    Returns the number of deals seeded."""
    conn = _connect(path)
    try:
        rows = conn.execute("SELECT deal_id FROM deals").fetchall()
        for row in rows:
            seed_dd_checklist(row["deal_id"], conn)
        conn.commit()
        return len(rows)
    finally:
        conn.close()


def _dd_item_row(row):
    return {
        "id": row["id"],
        "deal_id": row["deal_id"],
        "category": row["category"],
        "item_key": row["item_key"],
        "label": row["label"],
        "status": row["status"],
        "notes": row["notes"],
        "created_at": row["created_at"],
        "updated_at": row["updated_at"],
    }


def list_dd_items(deal_id, path=None):
    """Checklist items for a deal, in checklist order."""
    conn = _connect(path)
    try:
        rows = conn.execute(
            "SELECT * FROM dd_items WHERE deal_id = ? ORDER BY id",
            (deal_id,)).fetchall()
    finally:
        conn.close()
    return [_dd_item_row(r) for r in rows]


def dd_item_exists(deal_id, item_key, path=None):
    conn = _connect(path)
    try:
        row = conn.execute(
            "SELECT id FROM dd_items WHERE deal_id = ? AND item_key = ?",
            (deal_id, item_key)).fetchone()
    finally:
        conn.close()
    return row is not None


def set_dd_status(deal_id, item_key, status, path=None):
    """Human-controlled DD item status. Any transition is allowed; DD
    workflow state is tracked, not decided, by the engine."""
    if status not in DD_STATUSES:
        raise ValueError("Unknown DD status: %r" % (status,))
    conn = _connect(path)
    try:
        cur = conn.execute(
            "UPDATE dd_items SET status = ?, updated_at = ? "
            "WHERE deal_id = ? AND item_key = ?",
            (status, _now_iso(), deal_id, item_key))
        if cur.rowcount == 0:
            raise ValueError("Unknown DD item: %r" % (item_key,))
        conn.commit()
    finally:
        conn.close()
    return status


def set_dd_notes(deal_id, item_key, notes, path=None):
    conn = _connect(path)
    try:
        cur = conn.execute(
            "UPDATE dd_items SET notes = ?, updated_at = ? "
            "WHERE deal_id = ? AND item_key = ?",
            (notes or "", _now_iso(), deal_id, item_key))
        if cur.rowcount == 0:
            raise ValueError("Unknown DD item: %r" % (item_key,))
        conn.commit()
    finally:
        conn.close()


def add_dd_document(deal_id, item_key, filename, stored_path, note="",
                    path=None):
    """Record an uploaded DD document. Returns the document id."""
    conn = _connect(path)
    try:
        cur = conn.execute(
            """INSERT INTO dd_documents
               (deal_id, item_key, filename, stored_path, note, uploaded_at)
               VALUES (?, ?, ?, ?, ?, ?)""",
            (deal_id, item_key, filename, stored_path, note or "",
             _now_iso()))
        doc_id = cur.lastrowid
        conn.commit()
    finally:
        conn.close()
    return doc_id


def _dd_doc_row(row):
    return {
        "id": row["id"],
        "deal_id": row["deal_id"],
        "item_key": row["item_key"],
        "filename": row["filename"],
        "stored_path": row["stored_path"],
        "note": row["note"],
        "uploaded_at": row["uploaded_at"],
    }


def list_dd_documents(deal_id, item_key=None, path=None):
    conn = _connect(path)
    try:
        if item_key:
            rows = conn.execute(
                "SELECT * FROM dd_documents WHERE deal_id = ? AND item_key = ? "
                "ORDER BY id",
                (deal_id, item_key)).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM dd_documents WHERE deal_id = ? ORDER BY id",
                (deal_id,)).fetchall()
    finally:
        conn.close()
    return [_dd_doc_row(r) for r in rows]


def get_dd_document(doc_id, path=None):
    conn = _connect(path)
    try:
        row = conn.execute(
            "SELECT * FROM dd_documents WHERE id = ?", (doc_id,)).fetchone()
    finally:
        conn.close()
    return _dd_doc_row(row) if row else None


def dd_progress(deal_id, path=None):
    """Return (cleared_count, total_count) for a deal's DD checklist."""
    conn = _connect(path)
    try:
        row = conn.execute(
            "SELECT COUNT(*) AS total, "
            "SUM(CASE WHEN status = 'cleared' THEN 1 ELSE 0 END) AS cleared "
            "FROM dd_items WHERE deal_id = ?",
            (deal_id,)).fetchone()
    finally:
        conn.close()
    return (row["cleared"] or 0, row["total"] or 0)


def dd_progress_all(path=None):
    """Return {deal_id: (cleared, total)} for every deal with a checklist."""
    conn = _connect(path)
    try:
        rows = conn.execute(
            "SELECT deal_id, COUNT(*) AS total, "
            "SUM(CASE WHEN status = 'cleared' THEN 1 ELSE 0 END) AS cleared "
            "FROM dd_items GROUP BY deal_id").fetchall()
    finally:
        conn.close()
    return {r["deal_id"]: (r["cleared"] or 0, r["total"] or 0) for r in rows}
